/**
 * Deterministic seed SQL generation.
 *
 * Kept separate from the importer script so the escaping rules are unit tested.
 * The generated script replaces analytics rows only: llm_usage is never named,
 * because reloading data must not reset consumed model quota.
 */
import { DATA_VERSION, METRIC_VERSION } from "../shared/dataset.ts";
import type { OrderRow } from "./import.ts";

export const SEED_COLUMNS = [
  "order_id",
  "client_id",
  "order_date",
  "delivery_date",
  "carrier",
  "origin_city",
  "destination_city",
  "status",
  "sku",
  "product_category",
  "quantity",
  "unit_price_cents",
  "order_value_cents",
  "is_promo",
  "promo_discount_pct",
  "region",
  "warehouse",
  "delivery_days",
] as const;

export class SeedValueError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SeedValueError";
  }
}

/** Quote a text literal, doubling embedded single quotes. */
export function sqlText(value: string): string {
  if (/[\u0000\r\n]/.test(value)) {
    throw new SeedValueError(
      `Value contains an unsupported control character: ${JSON.stringify(value)}`,
    );
  }
  return `'${value.replace(/'/g, "''")}'`;
}

export function sqlNullableText(value: string | null): string {
  return value === null ? "NULL" : sqlText(value);
}

export function sqlNullableNumber(value: number | null): string {
  return value === null ? "NULL" : String(value);
}

export function buildSeedSql(
  rows: readonly OrderRow[],
  manifestJson: string,
  importedAt: string,
  options: { readonly chunkSize?: number } = {},
): string {
  // The manifest is stored as a single JSON text value. Compact it so a
  // pretty-printed manifest file can be passed directly: sqlText deliberately
  // refuses newlines in data values, and reformatting JSON is lossless.
  let compactManifest: string;
  try {
    compactManifest = JSON.stringify(JSON.parse(manifestJson));
  } catch {
    throw new SeedValueError("The manifest passed to buildSeedSql is not valid JSON.");
  }

  const chunkSize = options.chunkSize ?? 50;
  const lines: string[] = [
    "-- Generated by scripts/import-data.ts. Do not edit by hand.",
    `-- Data version ${DATA_VERSION}, metric version ${METRIC_VERSION}, imported ${importedAt}.`,
    "-- Replaces analytics rows only. The model usage table is deliberately left",
    "-- untouched so reloading data cannot reset consumed quota.",
    "DELETE FROM data_manifest;",
    "DELETE FROM orders;",
  ];

  for (let start = 0; start < rows.length; start += chunkSize) {
    const chunk = rows.slice(start, start + chunkSize);
    const values = chunk
      .map((row) =>
        [
          sqlText(row.order_id),
          sqlText(row.client_id),
          sqlText(row.order_date),
          sqlNullableText(row.delivery_date),
          sqlText(row.carrier),
          sqlText(row.origin_city),
          sqlText(row.destination_city),
          sqlText(row.status),
          sqlText(row.sku),
          sqlText(row.product_category),
          String(row.quantity),
          String(row.unit_price_cents),
          String(row.order_value_cents),
          String(row.is_promo),
          String(row.promo_discount_pct),
          sqlText(row.region),
          sqlText(row.warehouse),
          sqlNullableNumber(row.delivery_days),
        ].join(", "),
      )
      .map((tuple) => `  (${tuple})`)
      .join(",\n");
    lines.push(`INSERT INTO orders (${SEED_COLUMNS.join(", ")}) VALUES\n${values};`);
  }

  lines.push(
    `INSERT INTO data_manifest (id, manifest_json, imported_at) VALUES (1, ${sqlText(compactManifest)}, ${sqlText(importedAt)});`,
  );

  return `${lines.join("\n")}\n`;
}
